### ISSUE TITLE
empty tree's

### ISSUE THREAD

**Issue by glensc** [fragglet/agito#14]
so, i've using `FILTER_BRANCH_CALLBACKS` extensively to fix some weird move operations in svn history and omitting files.

sometimes it barfs out that some path can't be found, so i "fixed those" with:

```
    treedir.mkdir('htdocs/css')
    treedir.mkdir('htdocs/js')
    treedir.mkdir('config')
```

this has side effect that specific commit has `tree` items, but no items in it. this confuses other tools than git cli, i.e gitlab. git cli shows it "ok" only files:

```
[glen@blodnatt m]$ git ls-files
loader.js
main.js
module.js
[glen@blodnatt m]$ git ls-tree HEAD
040000 tree 4b825dc642cb6eb9a060e54bf8d69288fbee4904    bin
040000 tree 13d605bb985b69727b8f617d2842ab761adc0b1c    config
040000 tree c4c3486adb3f547fe2bbfee647478414e12013ff    htdocs
100644 blob 98e04e767f1f8d86881178b40b21a94658f4d285    loader.js
100644 blob ca466b257e2daa13e068ce4bb51717cf65b71d14    main.js
100644 blob dfd2342a526fbfbfd1e37ac40fc0f33911645713    module.js
040000 tree 4b825dc642cb6eb9a060e54bf8d69288fbee4904    tests
[glen@blodnatt m]$
```

so, gitlab also shows the "htdocs", but it's unable to navigate further in it, giving 404, which i believe is correct behaviour.

so, would it make sense to cleanup the tree of empty tree objects before making commit? as the tree can become empty by filter branch file rm as well.

**Comment by glensc** [comment]
if the error if is any use why i'm using `mkdir` hack, then here it is:

```
Traceback (most recent call last):
  File "./agito/agito.py", line 1297, in <module>
    head_id = get_history_for_path(path)
  File "./agito/agito.py", line 1106, in get_history_for_path
    return construct_history(path, commit_id, log)
  File "./agito/agito.py", line 981, in construct_history
    h = get_history_for_path("/dgs/frontend/trunk", 55867)
  File "./agito/agito.py", line 1106, in get_history_for_path
    return construct_history(path, commit_id, log)
  File "./agito/agito.py", line 888, in construct_history
    mutate_tree_from_log(treedir, path, entry)
  File "./agito/agito.py", line 412, in mutate_tree_from_log
    process_add_modify(treedir, filepath, log, changed_path)
  File "./agito/agito.py", line 355, in process_add_modify
    revision)
  File "./agito/agito.py", line 286, in add_to_tree_from_svn
    treedir[filepath] = (perms, blob_id)
  File "./agito/agito.py", line 123, in __setitem__
    subdir = self.__get_subdir(components[0])
  File "./agito/agito.py", line 86, in __get_subdir
    _, sha = self.tree[name]
  File "/usr/lib64/python2.7/site-packages/dulwich/objects.py", line 879, in __getitem__
KeyError: 'htdocs'
```

also second reason i'm using `treedir.mkdir` is because it behaves like:
`rm -rf htdocs; mkdir -p htdocs` without getting exceptions in the way, i'm using this part accidentally :)

**Comment by fragglet** [comment]
> this has side effect that specific commit has tree items, but no items in it

So, if I can re-state what I'm understanding here: empty directories cause a problem but you created the empty directories yourself using mkdir. Is that right? If so then that's not the real problem here.

Rather I'd like to concentrate on this part:

> sometimes it barfs out that some path can't be found

Rather than diagnosing your "fix" which clearly doesn't work, let's see if we can fix that properly.

**Comment by glensc** [comment]
I believe empty "dir objects" can happen also if filter-branch hook removes all files from path. did not test this though.

i agree and want to solve the actual problem. it's just hard to create reproducer that i can share publicly. but i will give it a try anyway.

**Comment by glensc** [comment]
ok here's reproducer: https://gist.github.com/glensc/df4f605603187c0d8f82866b2c0207f1

the hook point is to remove `/library/zend` from existence:

commit history is like:
- create_file some_dir/some_file
- create_file library/zend/file1
- update_file library/zend/file1
- update_file library/zend/file1
- update_file some_dir/some_file
- update_file library/zend/file1

to do that:

``` python

def my_filter_callback(path, entry, metadata, treedir):
    svn_rev = entry.revision.number
    svn_path = "%s@%s" % (path, svn_rev)

    if svn_rev >= 4:
        del treedir['library/zend']

FILTER_BRANCH_CALLBACKS = [my_filter_callback]
```

```
+ ./agito/agito.py bug-14.cfg
===== master
Constructing history from /project/trunk for 1..7
       1:
        A
        commit 057741ed68096fa4dc10ad6fa752cff186d660c2

       2:
        A empty_dir
        commit f9374def697c15d9d62e16c49f4d53b28edfc504

       3:
        A some_dir
        A some_dir/some_file
        commit cf64fb679a4677819fcb05bb454a763f2988c10e

       4:
        A library
        A library/zend
        A library/zend/file1
        commit 77fb27a29b5b9e2688178e68ef468be1039f7b9a

       5:
        M library/zend/file1
Traceback (most recent call last):
  File "./agito/agito.py", line 1085, in <module>
    head_id = get_history_for_path(path)
  File "./agito/agito.py", line 896, in get_history_for_path
    return construct_history(path, commit_id, log)
  File "./agito/agito.py", line 814, in construct_history
    mutate_tree_from_log(treedir, path, entry)
  File "./agito/agito.py", line 376, in mutate_tree_from_log
    log, changed_path)
  File "./agito/agito.py", line 332, in process_add_modify
    revision)
  File "./agito/agito.py", line 267, in add_to_tree_from_svn
    treedir[filepath] = (perms, blob_id)
  File "./agito/agito.py", line 109, in __setitem__
    subdir[components[1]] = value
  File "./agito/agito.py", line 108, in __setitem__
    subdir = self.__get_subdir(components[0])
  File "./agito/agito.py", line 74, in __get_subdir
    _, sha = self.tree[name]
  File "/usr/lib64/python2.7/site-packages/dulwich/objects.py", line 879, in __getitem__
KeyError: 'zend'
```

**Comment by glensc** [comment]
@fragglet ping https://github.com/fragglet/agito/issues/14#issuecomment-252179326
